build:
  tags:
    - shell-runner
  script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY 
    - make build
    - docker push $DOCKER_REGISTRY/group/project/image:latest