build:
  tags:
    - shell-runner
  script:
    - docker build . --squash -t andrewmontagne/byond:$CI_COMMIT_SHORT_SHA
    - docker push andrewmontagne/byond:$CI_COMMIT_SHORT_SHA
    - docker tag andrewmontagne/byond:$CI_COMMIT_SHORT_SHA andrewmontagne/byond:$CI_COMMIT_BRANCH
    - docker push andrewmontagne/byond:$CI_COMMIT_BRANCH
