build:
  tags:
    - shell-runner
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY 
    - make build
    - docker push $DOCKER_REGISTRY/group/project/image:latest