stages:
  - build
  - publish

build:
  stage: build
  tags:
    - shell-runner
  script:
    - docker build . --no-cache --squash -t andrewmontagne/byond:$CI_COMMIT_BRANCH

docker-hub:
  stage: publish
  tags:
    - shell-runner
  script:
    - docker push andrewmontagne/byond:$CI_COMMIT_BRANCH