build:
  tags:
    - shell-runner
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 
    - make build
    - docker push $CI_REGISTRY/group/project/image:latest