build:
  tags:
    - shell-runner
  script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login --username $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY 
    - docker build . -t andrewmontagne/byond:$CI_COMMIT_SHORT_SHA
    - docker push andrewmontagne/byond:$CI_COMMIT_SHORT_SHA