stages:
  - build
  - test
  - publish

build:
  stage: build
  tags:
    - shell-runner
  script:
    - docker pull debian:stable-slim
    - docker build . --no-cache --squash -t andrewmontagne/byond:$CI_COMMIT_BRANCH

test:
  stage: test
  tags:
    - shell-runner
  script:
    - docker run --rm andrewmontagne/byond:$CI_COMMIT_BRANCH bash -c "cd /byond/tests && source /byond/env.sh && /usr/bin/expect /byond/tests/test.expect"

docker-hub:
  stage: publish
  tags:
    - shell-runner
  script:
    - docker push andrewmontagne/byond:$CI_COMMIT_BRANCH